# permissions for end users to edit scalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deployment-scaling-operator
    app.kubernetes.io/part-of: deployment-scaling-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-editor-role
rules:
- apiGroups:
  - api.odogwuval.org
  resources:
  - scalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.odogwuval.org
  resources:
  - scalers/status
  verbs:
  - get
