apiVersion: api.odogwuval.org/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler
    app.kubernetes.io/instance: scaler-sample
    app.kubernetes.io/part-of: deployment-scaling-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: deployment-scaling-operator
  name: scaler-sample
spec:
  # TODO(user): Add fields here
